customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
        path("accounts/profile/",views.ProfileView.as_view(),name="profile"),
        path("accounts/login/",views.LoginView.as_view(),name='login'),
        path("accounts/logout/",views.logout_view,name='logout'),
        path("accounts/signup/",views.SignUpView.as_view(),name='signup'),
        path("accounts/confirm_email/",views.confirm_email_view,name='confirm_email'),
        path("accounts/verify_email/<secret_key>/",views.confirm_email_verification_view,name="verify_email"),
        path("notifications/",views.notification_list,name="notification_list"),
        path("notifications/<pk>/detail/",views.notification_detail,name="notification_detail"),
        ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
        path('',views.hero,name='hero'),
        path('store/',views.index,name='index'),
        #path('dashboard/',views.dashboard,name='dashboard'),
        ]

customers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.shortcuts import reverse
import uuid
# Create your models here.

def send_notification(user,msg,url,category="general"):
    """ same function in customers.utils, added here to bypass circular importation issues """
    notification = Notification.objects.create(user=user,message=msg,category=category,url=url)
    return True


class CustomUser(AbstractUser):
    user_type = models.CharField(blank=True,null=True,max_length=30)
    """def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        send_notification(self,"Account Created",reverse("customers:profile"))"""

    def save(self,*args,**kwargs):

        if self.pk:
            old_instance = CustomUser.objects.get(pk=self.pk)
            if old_instance.username != self.username:
                send_notification(self,"Username Updated",reverse("customers:profile"))

            if old_instance.email != self.email:
                send_notification(self,"Email Updated",reverse("customers:profile"),category="security")

            if old_instance.first_name != self.first_name:
                send_notification(self,"First Name Updated",reverse("customers:profile"),category="security")
                
            if old_instance.last_name != self.last_name:
                send_notification(self,"Last Name Updated",reverse("customers:profile"),category="security")


            if old_instance.password != self.password:
                send_notification(self,"Password Updated",reverse("customers:profile"),category="security")

        super().save(*args,**kwargs)

             
class Customer(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    address = models.CharField(max_length=150,blank=True,null=True)
    phone = models.PositiveIntegerField(blank=True,null=True)
    avatar = models.ImageField(upload_to="profile",null=True,blank=True)

    
    def __str__(self):
        return self.user.username

    """def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        send_notification(self,"Profile Created. Take a look at your profile",reverse("customers:profile"))
"""
    def save(self,*args,**kwargs):
 
        if self.pk:
            old_instance = Customer.objects.get(pk=self.pk)
            if old_instance.address != self.address:
                send_notification(self.user,"Address Updated",reverse("customers:profile"))
            if old_instance.phone != self.phone:
                send_notification(self.user,"Phone Updated",reverse("customers:profile"),category="security")
            if old_instance.avatar.name != self.avatar.name:
                send_notification(self.user,"Profile picture Updated",reverse("customers:profile"),category="security")
        super().save(*args,**kwargs)

    def avatar_url(self):
        try:
            return self.avatar.url
        except ValueError:
            return '/media/images/icons/person.svg'

class EmailVerification(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    secret_key = models.CharField(blank=True,max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    @property
    def has_expired(self):
        return timezone.now() - self.created > timezone.timedelta(minutes=10)
    def save(self,*args,**kwargs):
        self.secret_key =  str(uuid.uuid4())
        super().save(*args,**kwargs)


class Notification(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    message = models.CharField(max_length=100)
    category = models.CharField(max_length=30,null=True,blank=True,default="general")
    viewed = models.BooleanField(default=False)
    url = models.CharField(max_length=150,default="/")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"self.user.username => self.message"
    
    def mark_as_viewed(self):
        self.viewed = True

    def get_css_class(self):
        if self.viewed:
            return ""
        else:
            return "new-notification"
    class Meta:
        ordering = ["-created"]

customers/forms.py
from django import forms

class SignUpForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30,widget = forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=30)
    email = forms.EmailField()
    phone = forms.IntegerField(widget=forms.TelInput({"required":"false"}))
    delivery_address = forms.CharField(max_length=150,widget=forms.TextInput({"required":"false"}))

customers/views.py
from django.shortcuts import render
from .models import Customer,Notification, CustomUser
from django.views import View
from .forms import LoginForm, SignUpForm, ProfileForm
from django.shortcuts import reverse, redirect, get_object_or_404
from django.urls import resolve
from django.urls.exceptions import Resolver404
from urllib.parse import urlparse
from django.contrib.auth import login, logout, authenticate
from .utils import send_confirmation_email, verify_secret_key,send_notification
from datetime import timedelta
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required,name="dispatch")
class ProfileView(View):

    def get(self,request):
        
        fname = request.user.first_name
        lname = request.user.last_name
        username = request.user.username
        email = request.user.email
        cust = request.user.customer_set.all()[0]
        addr = cust.address
        phone = cust.phone

        profile_form = ProfileForm(initial={"first_name":fname,"last_name":lname,"username":username,"email":email,"delivery_address":addr,"phone":phone})
        context = {
                "profile_form":profile_form
                }
        return render(request,"customers/profile.html",context)

    def post(self,request):
        form = ProfileForm(request.POST)
        if form.is_valid():
            fname = form.cleaned_data.get("first_name")
            lname = form.cleaned_data.get("last_name")
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            addr  = form.cleaned_data.get("delivery_address")
            phone = form.cleaned_data.get("phone")
            # save changes
            user = request.user
            cust = user.customer_set.all()[0]
            user.first_name = fname
            user.last_name = lname
            user.username = username
            user.email = email
            cust.address = addr
            cust.phone = phone
            user.save()
            cust.save()
            context = {
                    "success" : "profile updated",
                    "profile_form" : form
                    }
            return render(request,"customers/profile.html",context)
        else:
            # if form is not valid
            context = {
                    "failure": "profile not updated",
                    "profile_form" : form,
                    }
            return render(request,"customers/profile.html",context)

@login_required
def notification_list(request):
    """ The notification instance would be automatically added by the context processor  customers.context_processor.notification.
    """
    return render(request,"customers/notification_list.html")

@login_required
def notification_detail(request,pk):
    """ This view is not a typical detail view, as it does not really renders a detail view of a notification instance, but confirms it was clicked or interacted with, therefore marking it as viewed. it redirects to the instance.url """
    instance = get_object_or_404(Notification,pk=pk,user=request.user)
    if not instance.viewed:
        instance.mark_as_viewed()
        instance.save()
    return redirect(instance.url)

class SignUpView(View):

    def get(self,request):
        form = SignUpForm()
        context = {
                "signupform":form
                }
        return render(request,"customers/signup.html",context)

    def post(self,request):
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = CustomUser.objects.create_user(username=username,password=password,first_name=first_name,last_name=last_name,email=email)
            user.is_active = False
            user.save()
            Customer.objects.create(user=user)
            request.session["email"] = email
            request.session["username"] = username
            request.session.set_expiry(timedelta(minutes=10)) 
            return redirect(reverse("customers:confirm_email"))
        else:
            context = {
                    "signupform":form,
                    "error":"invalid form data"
                    }
            return render(request,"customers/signup.html",context)

class LoginView(View):

    def get(self,request):
        form = LoginForm()
        context = {
                "loginform":form
                }
        return render(request,"customers/login.html",context)

    def post(self,request):
        
        form = LoginForm(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)

            if user:

                login(request,user)
                next_url = request.GET.get("next")
                if next_url:
                    try:
                        resolve(urlparse(next_url).path)
                        return redirect(next_url)
                    except Resolver404:
                        return redirect(reverse("store:index"))
                else:
                    return redirect(reverse("store:index"))

            else:
                try:
                    user = CustomUser.objects.get(username=username)
                    if not user.is_active:
                        request.session["email"] = user.email
                        request.session["username"] = username
                        request.session.set_expiry(timedelta(minutes=10))
                        return redirect(reverse("customers:confirm_email"))
                except CustomUser.DoesNotExist:
                    context = {
                            "loginform":form,
                            "error":"invalid credentials"
                            }
                    return render(request,"customers/login.html",context)

        else:
            context= {
                    "loginform":form,
                    "error":"invalid form data"
                    }
            return render(request,"customers/login.html",context)

@login_required
def logout_view(request):
    logout(request)

    return redirect(reverse("customers:login"))

    
def confirm_email_view(request):
    """ starts verification process"""
    email = request.session.get('email')
    username = request.session.get('username')
    if username is None:
        return redirect(reverse('customers:login'))
    request.session['username'] = username

    res = send_confirmation_email(email,username)
    msg ="A verification link has been emailed to you!"
    context = {
            "email":email,
            "msg": msg,
            }
    return render(request,"customers/confirm_email.html",context)


def confirm_email_verification_view(request,secret_key):
    """ confirm that the email has been clicked, """
    status, user = verify_secret_key(secret_key)
    if status:
        print("Email Verified!")
        user.is_active = True
        user.save()
        context = {
                "success" : "Email Verified Successfully"
                }
        return render(request,"customers/message.html",context)

    else:
        print("Verification failed")
        context = {
                "failed" : "Email Verification Failed"
                }
        return render(request,"customers/message.html",context)
        

customers/templates/customers/confirm_email.html
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vendora|confirm email</title>
  <style>
  body{
    margin: 0;
    padding: 10px;
    background-color: #fff;
    color: #333;
    font-size: 16px;
    font-family: serif;
  }
  header{
    display: block;
    width: 100%;
    height: 10vh;
    background-color: darkslateblue;
    color: #fff;
    border-radius: 15px;
  }
  h1{
    font-size: 16px;
    line-height: 10vh;
    height: 10vh;
    padding-left: 10px;
  }
  
  .msg{
    width: 80%;
    height: 30%;
    border-style: none;
    border-radius: 10px;
    box-shadow: 0 0 2px 2px #ccc;
    background-color: #ffffff;
    color: #222;
    margin: auto;
    margin-top:100px;
    padding:10px;
    text-align: center;
  }
  #success{
    color: green;
    
  }
  #failed{
    color: red;
  }
  .msg p{
    font-size: 24px;
  }
  .msg a{
    display: block;
    box-sizing: content-box;
    text-decoration: none;
    color: darkslateblue;
    border-style: solid;
    border-radius: 15px;
    border-width: 1px;
    width: 50%;
    height: 30px;
    line-height: 30px;
    margin: auto;
    border-color: darkslateblue;
  }
  </style>
{% load static %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'customers/css/base.css' %}">
</head>
<body>
  <header><h1>Vendora</h1></header>
  
 <main>
<form >
	{% csrf_token %}
  <div class="msg">
	<h2> Confirm Email </h2>
	<p>{{msg}}</p>
	<p>{{email}}</p>
  </div>
	</main>
 </body>
</html>

customers/templates/customers/login.html
{% extends "base.html" %}
  {% load static %}
{% load crispy_forms_tags %}

{% block styles %}
<link rel="stylesheet" href="{% static 'customers/css/base.css' %}">
{% endblock styles %}
{% block title %}Login{% endblock title %}
{% block nav %}
<header>
	<h1 id="brand-name"><a href="/">Vendora</a></h1>
</header>
{% endblock %}
{% block content %}
<main>
 	{% if error %}
	<div class="alert alert-danger popup">
			{{ error }}
	</div>
	{% endif %}
	
<form method="POST" action="" class="auth-form slidedown" id="login-form">
			<h2 class="form-heading">Log<span>in</span></h2> 

	{% csrf_token %}
	{{ loginform }}
		<br>
	<br>
	<button type="submit" >Login</button>
	<p> don't have an account?</p>
	<a href="{% url 'customers:signup' %}" >signup here</a>
</form>
	
	</main>
{% endblock content %}
  {% block scripts %}
  <script  src="{% static 'customers/js/confirm_password.js' %}"></script>
 
  {% endblock scripts %}

customers/templates/customers/message.html
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vendora</title>
  <style>
  body{
    margin: 0;
    padding: 10px;
    background-color: #fff;
    color: #333;
    font-size: 16px;
    font-family: serif;
  }
  header{
    display: block;
    width: 100%;
    height: 10vh;
    background-color: darkslateblue;
    color: #fff;
    border-radius: 15px;
  }
  h1{
    font-size: 16px;
    line-height: 10vh;
    height: 10vh;
    padding-left: 10px;
  }
  
  .msg{
    width: 80%;
    height: 30%;
    border-style: none;
    border-radius: 10px;
    box-shadow: 0 0 2px 2px #ccc;
    background-color: #ffffff;
    color: #222;
    margin: auto;
    margin-top:100px;
    padding:10px;
    text-align: center;
  }
  #success{
    color: green;
    
  }
  #failed{
    color: red;
  }
  .msg p{
    font-size: 24px;
  }
  .msg a{
    display: block;
    box-sizing: content-box;
    text-decoration: none;
    color: darkslateblue;
    border-style: solid;
    border-radius: 15px;
    border-width: 1px;
    width: 50%;
    height: 30px;
    line-height: 30px;
    margin: auto;
    border-color: darkslateblue;
  }
  </style>
</head>
<body>
  <header><h1>Vendora</h1></header>
  <main>
  {% if success %}
  <div class="msg" id="success"><p>{{success}}</p>
    <a href="/">Home</a>
  </div>
  {% else %}
    {% if failed %}
  <div class="msg" id="failed"><p>{{failed}}</p>
    <a href="{% url 'customers:login' %}">Re login</a>
  </div>
  {% endif %}
    {% endif %}
  </main>
</body>
</html>

customers/templates/customers/notification_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}notifications{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'customers/css/base.css' %}">
{% endblock styles %}
{% block content %}
<main>
  <h3>Notifications</h3>
{% if notification %}
<ul class="notification-ul">
  {% for item in notification %}
  <li class="notification-list-item {{item.get_css_class}}"><a class="notification-list-item-link" href="{% url 'customers:notification_detail' item.pk %}">
    {{item.message}}
  </a></li>
  {% endfor %}
</ul>
{% else %}
<div>No Notifications</div>
{% endif %}
</main>
{% endblock content %}

customers/templates/customers/profile.html
 {% extends "base.html" %}
{% load static crispy_forms_tags %}
{% block title %}profile{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'customers/css/base.css' %}">
{% endblock styles %}
{% block scripts %}
<script src="{% static 'customers/js/profile.js' %}" type="application/javascript"></script>
{% endblock scripts %}
{% block content %}
<main>
  {% if success %}
  <script type="application/javascript">
  if(!window.hasRunAction){
    window.hasRunAction = true;
    toast("{{success}}");
  }
  
  </script>
  {% else %}
  {% if failure %}
  <script type="application/javascript">
  toast("{{failure|escapejs}}");
  </script>
  {% endif %}
  {% endif %}
  <div>
  <img src="{{user.customer_set.all.0.avatar_url}}" alt="profile picture" id="profile-picture">
    <p id="username">{{user.username }}</p>
  </div>
  <section id="profile-form" class="auth-form">
    {% csrf_token %}
    {{ profile_form|crispy }}
    <br>
    <br>
    <button type="button" id="save-profile-btn">Save Changes</button>
  </section>
	</main>
{% endblock content %}

customers/templates/customers/signup.html
{% extends "base.html" %}
  {% load static %}
{% load crispy_forms_tags %}
{% block styles %}
<link rel="stylesheet" href="{% static 'customers/css/base.css' %}">
{% endblock styles %}
{% block title %}SignUp{% endblock title %}
{% block nav %}
<header>
	<h1 id="brand-name"><a href="/">Vendora</a></h1>
</header>
{% endblock %}
  {% block content %}
<main>
<form method="POST" action="" id='signup-form' class="auth-form slidedown">
		<h2 class="form-heading">Sign <span>Up</span></h2>
	{% if error %}
	{{error}}
	{% endif %}

	{% csrf_token %}
	
	<p id="error_msg_box"></p>
	
  {% for field in signupform %}
    <div class="form-group">     <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field.as_widget}}
      <div id="id_{{ field.name }}_errors" class="invalid-feedback d-block">
        {% if field.errors %}
          {% for error in field.errors %}
            <div>{{ error }}</div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  {% endfor %}

	<br>
	<br>
	<button type="submit" id="signup_button">Signup</button> 

	<p> already have an account?</p>
	<a href="{% url 'customers:login' %}" >login</a>
</form>
	
	</main>
  {% endblock content %}
  {% block scripts %}
  <script  src="{% static 'customers/js/confirm_password.js' %}"></script>
  {% endblock %}