customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
        path("accounts/profile/",views.ProfileView.as_view(),name="profile"),
        path("accounts/login/",views.LoginView.as_view(),name='login'),
        path("accounts/logout/",views.logout_view,name='logout'),
        path("accounts/signup/",views.SignUpView.as_view(),name='signup'),
        path("accounts/confirm_email/",views.confirm_email_view,name='confirm_email'),
        path("accounts/verify_email/<secret_key>/",views.confirm_email_verification_view,name="verify_email"),
        path("notifications/",views.notification_list,name="notification_list"),
        path("notifications/<pk>/detail/",views.notification_detail,name="notification_detail"),
        ]

myadmin/urls.py
from django.urls import path
from . import views

app_name = "myadmin"

urlpatterns = [
        path('dashboard/',views.DashboardView.as_view(),name="dashboard"),
        path('api/live-sales/',views.sales_view,name='live-sales'),
        path('dashboard/product/',views.product_view,name="product"),
        path('dashboard/inventory/',views.inventory_view,name="inventory"),
        path('dashboard/category/',views.category_view,name="category"),


        ]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
        path("<pk>/detail/",views.detailView,name="detail"),
        path("categories/",views.CategoryListView.as_view(),name="categories"),
        path("categories/<category_name>/",views.category_products_view,name="category_products"),
        path("search/",views.search_view,name="product_search")
        ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
        path('',views.hero,name='hero'),
        path('store/',views.index,name='index'),
        #path('dashboard/',views.dashboard,name='dashboard'),
        ]

myadmin/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from customers.models import Customer
from django.shortcuts import reverse

# Create your models here.

class Product(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ManyToManyField("Category")
    price = models.IntegerField(help_text='in Naira')
    image = models.ImageField(upload_to='products',null=True,blank=True)
    discount = models.IntegerField(validators=[MinValueValidator(1,message='min value is 1%'),MaxValueValidator(100,message='max value is 100%')],help_text='in percent',null=True,blank=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.name

    def get_discount_price(self):
        if discount:
            return  self.price - (self.price * (discount/100))
    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk":self.id})

    def get_rating(self):
        reviews = self.review_set.all()
        if len(reviews)==0:
            return None
        else:
            rating = sum([x.rating for x in reviews])/len(reviews)
            return rating

    def get_quantity_in_inventory(self):
        try:
            quantity = None if self.inventory.quantity==0 else self.inventory.quantity
        except:
            return None

        return quantity


    class Meta:
        ordering = ['-created']

class Category(models.Model):
    name = models.CharField(max_length=100,unique=True,null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:category_products",kwargs={"category_name":self.name})

    class Meta:
        verbose_name_plural = "Categories"



class Inventory(models.Model):
    product = models.OneToOneField(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name}=> {self.quantity}"

    class Meta:
        verbose_name_plural = "Inventories"


class Review(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    text = models.TextField(default="")
    rating = models.IntegerField(validators=[MaxValueValidator(5)],default=5)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer.user.username[:10]}=>{self.product.name}"

myadmin/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import  LoginRequiredMixin,UserPassesTestMixin
from django.utils.decorators import method_decorator
from products.models import Product, Category, Inventory
from customers.models import Customer
from django.http import JsonResponse
import random


class DashboardView(LoginRequiredMixin,UserPassesTestMixin , View):
    """ This view is the admin dashboard."""
    
    def test_func(self):
        # change is_supeeuser to groups
        return self.request.user.is_superuser

    def get(self,request):
        products = Product.objects.all()
        customers = Customer.objects.all()

        context = {
                "products" : products,
                "customers" : customers
                }
        return render(request,"myadmin/dashboard.html",context)

    def post(self,request):
        pass

def sales_view(request):

    data = [{"time": f"{hour:02d}:00", "value": random.randint(100, 400)}for hour in range(9, 24) ]

    return JsonResponse(data,safe=False)

def product_view(request):
    products = Product.objects.all()
    context = {
            "products" : products,
            }
    return render(request,"myadmin/products.html",context)

def inventory_view(request):
    inventory = Inventory.objects.all()
    context = {
            "inventory" : inventory,
            }
    return render(request,"myadmin/inventory.html",context)

def category_view(request):
    categories = Category.objects.all()
    context = {
            "categories" : categories,
            }
    return render(request,"myadmin/category.html",context)

products/views.py
from django.shortcuts import render 
from .models import Product,Category
from django.views.generic import ListView
from .utils import get_product_reviews, get_products_by_category
from django.http import JsonResponse
import base64

def detailView(request,pk):
    product = Product.objects.get(id=pk)
    reviews = get_product_reviews(product)
    
    context = {
            "product" : product,
            "product_reviews" : reviews,
            }
    return render(request,"products/detail.html",context)

class CategoryListView(ListView):
    model = Category
    template_name = "products/category_list.html"
    object_name = "category_list"

def category_products_view(request,category_name):
    
    products = get_products_by_category(category_name)
    context = {
            "products":products,
            "category":category_name,
            }
    """This view renders a template that uses a template partial, so the key "products" and any other key must be cobsistent"""
    return render(request,"products/category_products.html",context)

def search_view(request):

    q = request.GET.get("q")
    filter_q = request.GET.get("filter")
    if filter_q:
        print("FILTER "+filter_q)
        prod = get_products_by_category(filter_q)
        res = prod.filter(name__contains=q)
    else:
        res = Product.objects.filter(name__icontains=q) if bool(q.strip()) else []

    res = [{'name':x.name,'url':x.get_absolute_url()} for x in res] if len(res)>0 else {"empty":f"no result matching the query '{q}' was found"}

    result = {
            "result" : res }
    return JsonResponse(result)

myadmin/templates/myadmin/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  
  <title>admin|{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'myadmin/css/main.css' %}">
<link rel="stylesheet" href="{% static 'myadmin/css/navbar.css' %}">
  
  {% block styles %}{% endblock styles %}
 
</head>
<body>
  {% include "myadmin/navbar.html" %}
  
  {% block content %}
  {% endblock content %}
  
   <footer>
        <ul>
            <li>twitter</li>
            <li>facebook</li>
            <li>amazon</li>
        </ul>
        <p class="copyrt">granzularcodex&copy;<span id="year"></span></p>
        
        <script type="text/javascript">
let date = new Date();
document.querySelector("#year").innerHTML = date.getFullYear();
</script>
    </footer>
  
</body>

<script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
{% block scripts %}{% endblock scripts %}
   
</html>

myadmin/templates/myadmin/category.html
 {% extends "myadmin/base.html" %}
{% load static humanize %}
{% block title %}products{% endblock title %}
{% block styles %}
{% endblock styles %}

{% block content %}
<main class="main">
  <section class="top">
    
  </section>
  
  <section class="category-list">
  </section>
</main>
{% endblock content %}

myadmin/templates/myadmin/dashboard.html
{% extends "myadmin/base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block scripts %}
<script type="application/javascript" src="{% static 'myadmin/js/apexcharts.min.js' %}"></script>

<script type="application/javascript" src="{% static 'myadmin/js/chart.js' %}"></script>

<script type="application/javascript" src="{% static 'myadmin/js/main.js' %}"></script>
{% endblock scripts %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'myadmin/css/dashboard.css' %}">
{% endblock styles %}

{% block content %}
<!-- main content starts here-->
<main class="main">
  
  <!-- metrics and charts -->
  <section id="stats" class="section stats scroll-x">
    
    <div class="stat-item">
      <div class="metrics">
      <p class="title" >Customers</p>
         <img class="icon" src="/media/images/icons/person-fill.svg">
        <p class="count" id="total-customers-count">500</p>
    </div>
    </div>
    
    <div class="stat-item">
      <div class="metrics">
       <p class="title">Total Sales</p>
        <img class="icon" src="/media/images/sales01.png">
        <p class="count" id="total-sales-count">700</p>
      </div>
    </div>
    
    <div class="stat-item">
      <div class="metrics">
       <p class="title" >Total Revenue</p>
        <img class="icon" src="/media/images/revenue01.png">
        <p class="count" id="total-revenue-count scroll-x">₦500000</p>
      </div>
    </div>   
  </section>
  <!--chart-->
  <div id="sales-chart" class="section chart"></div>
  <!-- end of chart --> 
  <!--this section holds major ctas Products, Inventory, Categories-->
  <section class="main-section">
  <section id="inventory" class="section inventory">
    <div class="info">
      <h3>Inventory</h3>
    </div>
    <div class="cta">
      <button id="manage-inventory-btn" class="manage-btn" >manage</button>
    </div>
  </section>
  
  <section id="products" class="section products">
    <div class="info">
      <h3>Products</h3>
    </div>
    <div class="cta">
      <button id="manage-product-btn" class="manage-btn">manage</button>
    </div>
  </section>
  
  <section id="categories" class="section categories">
    <div class="info">
      <h3>Categories</h3>
    </div>
    <div class="cta">
      <button id="manage-category-btn" class="manage-btn">manage</button>
    </div>
  </section>
    
  </section>
  
</main>
{% endblock content %}

myadmin/templates/myadmin/inventory.html
{% extends "myadmin/base.html" %}
{% load static humanize %}
{% block title %}products{% endblock title %}
{% block styles %}
{% endblock styles %}

{% block content %}
<main class="main">
  <section class="top">
    
  </section>
  
  <section class="product-list">
    {% if products %}
    {% for product in products %}
    <div class="product-section">
      <div class="product-card">
        <img src="{{product.image.url}}">
        <p>{{product.name}}</p>
        <p>{{product.price|intcomma}}</p>
        
      </div>
      <div class="cta">
        <button>edit product</button>
        <button>delete product</button>
        
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="alert alert-warning"> No products</div>
    {% endif %}
  </section>
</main>
{% endblock content %}

myadmin/templates/myadmin/navbar.html
<header>
		<div class="cont" id="head">
			<h1 id="brand-name"><a href="{% url 'myadmin:dashboard' %}">Vendora ADMIN</a></h1>
<nav class="navbar">
	<ul>
				<li><a href="" class="nav-link">store</a></li>
		<li><a href="/" class="nav-link" >site</a></li>
				
	</ul>
			<div class="shot-cont">
							 
							<a href="{% url 'customers:profile' %}"
										class="shot-link not">
										<img class="shot" id="navbar-headshot"src="/media/images/icons/person.svg"><p class="notification-dot"></p></a>
								<a href="{% url 'customers:notification_list' %}"
										class="shot-link not">
										<img class="shot" id="navbar-bell"src="/media/images/icons/bell.svg"><p class="notification-dot" id="bell-dot"></p></a>
						
					<img class="menuicon" id="menu-icon" src="/media/images/menuicon01.png">
			</div>
			</div>
</nav>
			{% if user.is_authenticated %}
			
			{% else %}
						<div class="btn-cont">
			<a class="btn btn-register" href="{% url 'customers:signup' %}">Register</a>|<a class="btn btn-login" href="{% url 'customers:login' %}">Login</a>
										</div>
			{% endif %}
</header>

myadmin/templates/myadmin/products.html
{% extends "myadmin/base.html" %}
{% load static humanize %}
{% block title %}products{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'myadmin/css/products.css' %}">
{% endblock styles %}

{% block content %}
<main class="main">
  <section class="top-section">
    
  </section>
  
  <section class="product-list">
    {% if products %}
    {% for product in products %}
    <div class="product-section">
      <div class="product-card">
        <img src="{{product.image.url}}">
        <div class="product-info">
        <p>{{product.name}}</p>
        <p>₦{{product.price|intcomma}}</p>
          <a href="{{product.get_absolute_url}}">view</a>
        </div>
      </div>
      <div class="cta">
        <button class="btn edit-product-btn">edit product</button>
        <button class="delete-product-btn btn">delete product</button>
        
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="alert alert-warning"> No products</div>
    {% endif %}
  </section>
</main>
{% endblock content %}