customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
        path("accounts/profile/",views.ProfileView.as_view(),name="profile"),
        path("accounts/login/",views.LoginView.as_view(),name='login'),
        path("accounts/logout/",views.logout_view,name='logout'),
        path("accounts/signup/",views.SignUpView.as_view(),name='signup'),
        path("accounts/confirm_email/",views.confirm_email_view,name='confirm_email'),
        path("accounts/verify_email/<secret_key>/",views.confirm_email_verification_view,name="verify_email"),
        path("notifications/",views.notification_list,name="notification_list"),
        path("notifications/<pk>/detail/",views.notification_detail,name="notification_detail"),
        ]

orders/urls.py
from django.urls import path
from .views  import views,api

app_name = "orders"

urlpatterns = [
        path("<status>/list/",views.orders_list_view,name="list"),
        path("<pk>/detail/",views.orders_detail_view,name="detail"),
        path("cart-view/",views.cart_view,name="cart_view"),
        path("checkout/",views.checkout,name="checkout"),
        path("checkout/verify-payment/",views.verify_payment,name="verify_payment"),
        path("checkout/paystack/webhook/",views.paystack_webhook,name="paystack_webhook")
        
        ]
## DRF APIs View
urlpatterns += [
        path("api/cart/",api.CartView.as_view(),name="api-cart-view"),
        path("api/cart/<int:pk>/",api.CartView.as_view(),name="api-cart-patch-put-delete"),

        path("api/cart/bulk-create/",api.bulk_create_cart,name="bulk-cart-create"),
        path("api/cart/bulk-update/",api.bulk_update_cart,name="bulk-cart-update"),
        path("api/cart/bulk-delete/",api.bulk_delete_cart,name="bulk-cart-delete"),

        path("api/cart/custom/",api.cart_view,name="custom-cart-get"),
        ]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
        path("<pk>/detail/",views.detailView,name="detail"),
        path("categories/",views.CategoryListView.as_view(),name="categories"),
        path("categories/<category_name>/",views.category_products_view,name="category_products"),
        path("search/",views.search_view,name="product_search")
        ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
        path('',views.hero,name='hero'),
        path('store/',views.index,name='index'),
        #path('dashboard/',views.dashboard,name='dashboard'),
        ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="">
    <title>Vendora|{% block title %}{% endblock title %}</title>
  
    <link rel="icon" href="">
  <link rel="stylesheet" href="{% static 'css/utils.css' %}">
     <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
     <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
   <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <!-- Important Script -->
  <script type="application/javascript" src="{% static 'js/utils.js' %}"></script>
      
  </body>
</html>
    {% block styles %}
    {% endblock styles %}

</head>
<body>
    {% block nav %}
	{% include 'navbar.html' %}
    {% endblock nav %}
    
	{% block content %}

	{% endblock content %}
    
    
    <input hidden id="csrftoken" value="{{csrf_token}}">
    <footer>
        <ul>
            <li>twitter</li>
            <li>facebook</li>
            <li>amazon</li>
        </ul>
        <p class="copyrt">granzularcodex&copy;<span id="year"></span></p>
        
        <script type="text/javascript">
let date = new Date();
document.querySelector("#year").innerHTML = date.getFullYear();
</script>
    </footer>
</body>

{% if user.is_authenticated %}
  <script type="text/javascript" src="{% static 'orders/js/cart.js' %}"></script>
{% if new_notification %}
<script type="application/javascript">
let n = document.querySelector("#bell-dot");
n.textContent = "{{new_count|escapejs}}";
n.style.display = "inline-flex";
</script>
{% endif %}
{% else %}
<script type="text/javascript">
function add_to_cart(e){
  toast("Sign in to add to cart!")
}
try{
  [...document.querySelectorAll(".add-to-cart-btn")].map((el)=>{el.addEventListener("click",add_to_cart)});
}
catch{}
</script>
{% endif %}
     <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
	{% block scripts %}
	{% endblock scripts %}
</html>

templates/navbar.html
<header>
		<div class="cont" id="head">
			<h1 id="brand-name"><a href="{% url 'store:index' %}">Vendora</a></h1>
<nav class="navbar">
	<ul>
				<li><a href="{% url 'store:index' %}" class="nav-link">store</a></li>
		<li><a href="{% url 'products:categories' %}" class="nav-link" >categories</a></li>
						{% if user.is_authenticated %}
		<li><a href="{% url 'orders:list' 'all' %}" class="nav-link">orders</a></li>
				<li><a class="nav-link" id="btn-logout" href="{% url 'customers:logout' %}">logout</a></li>
				{% endif %}
	</ul>
			<div class="shot-cont">
							<a href="{% url 'orders:cart_view' %}" class="shot-link not"><img class="shot" id="navbar-cart-icon"src="/media/images/icons/cart3.svg"><p id="cart-cnt" class="notification-dot"></p></a>
							
							<a href="{% url 'customers:profile' %}"
										class="shot-link not">
										<img class="shot" id="navbar-headshot"src="/media/images/icons/person.svg"><p class="notification-dot"></p></a>
								<a href="{% url 'customers:notification_list' %}"
										class="shot-link not">
										<img class="shot" id="navbar-bell"src="/media/images/icons/bell.svg"><p class="notification-dot" id="bell-dot"></p></a>
						
					<img class="menuicon" id="menu-icon" src="/media/images/menuicon01.png">
			</div>
			</div>
</nav>
			{% if user.is_authenticated %}
			
			{% else %}
						<div class="btn-cont">
			<a class="btn btn-register" href="{% url 'customers:signup' %}">Register</a>|<a class="btn btn-login" href="{% url 'customers:login' %}">Login</a>
										</div>
			{% endif %}
			
			<div id="search-cont">
				<input placeholder="search for a product" type="text" id="search-box">
				<img id="search-icon" src="/media/images/icons/search.svg">
			</div>
			<section id="search-result-section-cont">
        <div class="search-header">
            
      <h3>Search Results</h3>
            <button id="close-search-btn"></button>
        </div>
            <div class="filter-cont">
                <h5>filter by category</h5>
            			
            						<select id="filter">
            									<option value="all">all</option>
            									{% for category in categories %}
            										<option value="{{category}}">{{category}}</option>
            									{% endfor %}            									
            						</select>
            		
            </div>
						<hr>
        <div id="search-result-section"></div>
    </section>
</header>