products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
        path("<pk>/detail/",views.detailView,name="detail"),
        path("categories/",views.CategoryListView.as_view(),name="categories"),
        path("categories/<category_name>/",views.category_products_view,name="category_products"),
        path("search/",views.search_view,name="product_search")
        ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
        path('',views.hero,name='hero'),
        path('store/',views.index,name='index'),
        #path('dashboard/',views.dashboard,name='dashboard'),
        ]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from customers.models import Customer
from django.shortcuts import reverse

# Create your models here.

class Product(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ManyToManyField("Category")
    price = models.IntegerField(help_text='in Naira')
    image = models.ImageField(upload_to='products',null=True,blank=True)
    discount = models.IntegerField(validators=[MinValueValidator(1,message='min value is 1%'),MaxValueValidator(100,message='max value is 100%')],help_text='in percent',null=True,blank=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.name

    def get_discount_price(self):
        if discount:
            return  self.price - (self.price * (discount/100))
    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk":self.id})

    def get_rating(self):
        reviews = self.review_set.all()
        if len(reviews)==0:
            return None
        else:
            rating = sum([x.rating for x in reviews])/len(reviews)
            return rating

    def get_quantity_in_inventory(self):
        try:
            quantity = None if self.inventory.quantity==0 else self.inventory.quantity
        except:
            return None

        return quantity


    class Meta:
        ordering = ['-created']

class Category(models.Model):
    name = models.CharField(max_length=100,unique=True,null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:category_products",kwargs={"category_name":self.name})

    class Meta:
        verbose_name_plural = "Categories"



class Inventory(models.Model):
    product = models.OneToOneField(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name}=> {self.quantity}"

    class Meta:
        verbose_name_plural = "Inventories"


class Review(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    text = models.TextField(default="")
    rating = models.IntegerField(validators=[MaxValueValidator(5)],default=5)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer.user.username[:10]}=>{self.product.name}"

products/views.py
from django.shortcuts import render 
from .models import Product,Category
from django.views.generic import ListView
from .utils import get_product_reviews, get_products_by_category
from django.http import JsonResponse
import base64

def detailView(request,pk):
    product = Product.objects.get(id=pk)
    reviews = get_product_reviews(product)
    
    context = {
            "product" : product,
            "product_reviews" : reviews,
            }
    return render(request,"products/detail.html",context)

class CategoryListView(ListView):
    model = Category
    template_name = "products/category_list.html"
    object_name = "category_list"

def category_products_view(request,category_name):
    
    products = get_products_by_category(category_name)
    context = {
            "products":products,
            "category":category_name,
            }
    """This view renders a template that uses a template partial, so the key "products" and any other key must be cobsistent"""
    return render(request,"products/category_products.html",context)

def search_view(request):

    q = request.GET.get("q")
    filter_q = request.GET.get("filter")
    if filter_q:
        print("FILTER "+filter_q)
        prod = get_products_by_category(filter_q)
        res = prod.filter(name__contains=q)
    else:
        res = Product.objects.filter(name__icontains=q) if bool(q.strip()) else []

    res = [{'name':x.name,'url':x.get_absolute_url()} for x in res] if len(res)>0 else {"empty":f"no result matching the query '{q}' was found"}

    result = {
            "result" : res }
    return JsonResponse(result)

products/templates/products/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}product categories{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'products/css/base.css' %}">
{% endblock styles %}
{% block content %}
<main>
<h2 class="heading">Categories</h2>
{% if category_list %}
	<div class="category-list">
{% for category in category_list %}
	<div class="item" ><a href="{{category.get_absolute_url}}" >{{category}}</a></div>
{% endfor %}
	</div>
{% else %}
<div>No Available Categories </div>
{% endif %}
	</main>
{% endblock content %}

products/templates/products/category_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{category}}-category{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'products/css/base.css' %}">
{% endblock styles %}
{% block content %}
<main>
<h2 class="category-tree"><a href="{% url 'products:categories'  %}">categories</a> > {{ category }}</h2>
  <hr/><br/>
{% include "products/partials/product_list.html" %}
</main>
{% endblock content %}

products/templates/products/detail.html
{% extends "base.html" %}
{% load static humanize %}
{% block title %}product-detail{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'products/css/detail.css' %}">
{% endblock styles %}

{% block content %}
<main>
	
<div class="container">
	<div class="product-container">
			<img class="product-image" src="{{product.image.url}}">
		<p class="label">Name</p>
			<p>{{ product.name }}</p>
		<p class="label">Description</p>
	<p>{{ product.description}}</p>
		<p><b>rating: </b><span>{% if product.get_rating %}{{ product.get_rating }}{% else %} no ratings {% endif %} </span></p>
		<p><b>units left: </b> <span class="product-units-left">{{product.get_quantity_in_inventory}} </span></p>
	<p class="label"><b>price: </b>₦{{product.price|intcomma}}</p> 
</div>
<div id="review-section" class="container">
	<h3>Reviews</h3>
	{% if product_reviews %}
	{% for review in product_reviews %}
<h3 class="reviewer-name">{{ review.customer.user.username }}</h3>
	<p class="review-text">{{ review.text }}</p>
	<p>Rating: {{ review.rating }}</p>

	{% endfor %}
	{% else %}
	No Reviews available
	{% endif %}
</div>
</div>
		<br>
	<button class="add-to-cart-btn" id="{{product.id}}" >add to cart</button>	
</main>
{% endblock content %}